name: 'Lamda deployed with ci-cd'

on:
  push:
     branches:
       - test
       - master

jobs:
   deploy:
      runs-on: ubuntu-latest
      #To spin up a machine to run these commands and it will be ubuntu m/c

      steps:
        - name: Checkout code
          uses: actions/checkout@v5   
          
        - name: Set up Python 3.11
          uses: actions/setup-python@v5 # Use a recent stable version of the action
          with:
             python-version: '3.11'  

        - name: Install dependencies
          run: |
            sudo apt-get update   
            sudo apt-get install -y  jq zip

        - name: Package the lambda function
          run: |
            python -m venv venv
            source venv/bin/activate 
            cd lambda_function
            mkdir package
            pip install --no-cache-dir -r requirements.txt -t ./package
            mv app.py ./package
            cd package 
            zip -r ../../lambda_handler.zip .
            cd ../..

        - name: Copy the environment variables
        #To dynamically set environment variables in github actions runner..
          run: |    
            echo "Current branch is : ${{ github.ref_name }}"
            if [ "${{ github.ref_name }}" == "master" ]; then 
              echo "ENV=PROD" >> $GITHUB_ENV
              echo "API_KEY=main_api" >> $GITHUB_ENV
              echo "LOG_LEVEL=INFO" >> $GITHUB_ENV
            
            else
              echo "ENV=test" >> $GITHUB_ENV
              echo "API_KEY=test_api" >> $GITHUB_ENV
              echo "LOG_LEVEL=INFO" >> $GITHUB_ENV
            
            fi  
        - name: Deploy lambda
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION : ap-south-1
          run: |
            FUNCTION_NAME="lambda_function_${{ github.ref_name }}"
            REGION="ap-south-1"

            FUNCTION_EXISTS=$(aws lambda get-function --function-name $FUNCTION_NAME --region $REGION || echo "false")
            
            echo "Function exists : $FUNCTION_EXISTS"

            if [ "$FUNCTION_EXISTS" == "false" ]; then
               aws lambda create-function \
                  --function-name $FUNCTION_NAME \
                  --runtime python3.11 \
                  --region $REGION \
                  --timeout 240 \
                  --zip-file fileb://lambda_handler.zip \
                  --handler app.lambda_event \
                  --role arn:aws:iam::686255953563:role/service-role/demoFunction-role-uteyqz1q \
                  --environment "Variables={ENV=${{ env.ENV }},API_KEY=${{ env.API_KEY }},LOG_LEVEL=${{ env.LOG_LEVEL }}}"
            else
              aws lambda update-function-code \
                   --function-name $FUNCTION_NAME --region $REGION \
                   --zip-file fileb://lambda_handler.zip
                   
            
              echo "Checking if the code updation or function creation has completed"
              while true;
              do 
                last_update= $(aws lambda get-function --function-name $FUNCTION_NAME --region $REGION --query 'Configuration.LastUpdateStatus')
                if [ "$last_update" == "Successful" ]; then 
                  echo "Lambda has been successfully created or updated"
                  break
              
                elif [ "$last_update" == "Failed" ]; then
                  echo "Function update has failed"
                  exit 1

                elif [ "$last_update" == "InProgress" ]; then 
                  sleep 2 

                fi    
              done
              
              aws lambda update-function-configuration \
                  --function-name $FUNCTION_NAME --region $REGION \
                  --timeout 300 --environment "Variables={ENV=${{ env.ENV }},API_KEY=${{ env.API_KEY }},LOG_LEVEL=${{ env.LOG_LEVEL }}}"      
            fi
                

              

            



                